server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: D:\\project-0211\\rsa\\rsa.pub
    priKeyPath: D:\\project-0211\\rsa\\rsa.pri
    secret: 23409LJDSI#(*)#*kfdsl23499DSDw4823@@Dl
    expire: 180
    cookieName: GMALL_TOKEN
    unick: unick
