server:
  port: 18081
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: pms-service-fescar-service-group
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
    publisher-confirm-type: CORRELATED
    publisher-returns: true
